version: "3.3"

services:
 nginx:
  image: nginx:latest
  volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./data/html:/var/www/html
    - ./var/log/nginx:/var/log/nginx
  ports:
    - 8080:80
  links:
    - wordpress

 mysql:
  image: mariadb
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 1
    MYSQL_DATABASE: db_wordpress
    MYSQL_USER: 1
    MYSQL_PASSWORD: 1
  restart: always


 wordpress:
  image: wordpress:php7.4-fpm-alpine
  volumes:
    - ./data/html:/var/www/html
  depends_on:
    - mysql
  environment:
    WORDPRESS_DB_HOST: mysql
    MYSQL_ROOT_PASSWORD: 2
    WORDPRESS_DB_NAME: db_wordpress
    WORDPRESS_DB_USER: 2
    WORDPRESS_DB_PASSWORD: 
    WORDPRESS_TABLE_PREFIX: wp_
  links:
    - mysql
  restart: always

 pma:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql:mysql
  ports:
    - 8081:80
  environment:
    PMA_HOST: mysql
    MYSQL_USERNAME: 3
    MYSQL_ROOT_PASSWORD: 3

